version: 2
jobs:
    build_and_test:
        machine:
            enabled: true
        steps:
            - checkout
            - run: echo "build rtmp-server"
            - run: cd trunk && cmake . && make && ./objs/utest_rs_server


workflows:
    version: 2
    build:
        jobs:
            - build_and_test
