version: 2
jobs:
    build-job:
        machine:
            enabled: true
        steps:
            - checkout
            - run: echo "build rtmp-server"
            - run: cd trunk && cmake . && make

workflows:
    version: 2
    build:
        jobs:
            - build-job
